# COPY THIS FILE TO docker-compose.user.yaml
# AND FILL IN THE VOLUMES WITH DATAPATH YOU WANT TO MOUNT TO DEV CONTAINER.

services:
  dev-unified-entry:
    network_mode: host
    
    volumes:
      - /media/yutianch/datasets/TartanAir/tartanair_v1:/data/tartanair_v1
      - /media/yutianch/datasets/DTU_MVS/:/data/dtu_mvs
